## Practice Notebook

### Introduction to Numpy
NumPy (Numerical Python) is a python library for scientific computing, that provides high-performance vectors, matrices and higher-dimensional data structures for Python.

## Numpy

####  Exercise 1: Import the numpy package as np.

Hint: use 'import … as …'

In [ ]:
import numpy as np

####  Exercise 2: Print the numpy version and the configuration.

Hint: np.\_\_version__, np.show_config

In [ ]:
print(np.__version__)
print(np.show_config())

1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### Exercise 3: Create an array of 10 zeros and 20 ones.

Hint: np.zeros, np.ones

In [ ]:
arr = np.zeros((5,5,5))
print(arr)
print(arr.shape)
arr = np.ones(20)
print(arr)
print(arr.shape)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
(5, 5, 5)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
(20,)


####  Exercise 4: Create a vector with values ranging from 10 to 49.

Hint: np.arange

In [ ]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


####  Exercise 5: Reverse a vector (first element becomes last).

Hint: np.array[::-1]

In [ ]:
print(x[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


####  Exercise 6: Find the indices of the non-zero elements from [1, 2, 0, 0,  4, 0].

Hint: np.nonzero

In [ ]:
arr = np.array([1,2,0,0,4,0])
print(np.nonzero(arr))
print([arr[i] for i in np.nonzero(arr)])

(array([0, 1, 4]),)
[array([1, 2, 4])]


####  Exercise 7: Create a 3x3 identity matrix.

Hint: np.eye

In [ ]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Exercise 7: Generate a random number between 0 and 1 using numpy.

Hint: np.random.rand()

In [ ]:
a = np.random.rand(5)
print(a)

[0.17623883 0.34648692 0.62070508 0.03168488 0.6608495 ]


####  Exercise 8: Create a 10x10 array with random values, find the minimum and the maximum values.

Hint: min, max

In [ ]:
arr = np.random.random((10,10))
print(arr)
print(arr.min(), arr.max())

[[0.17023589 0.97554319 0.747162   0.1040845  0.79802527 0.00783399
  0.58940833 0.40988985 0.47747431 0.42907859]
 [0.32842863 0.40800693 0.15234017 0.01958619 0.26625953 0.3683506
  0.03855371 0.02356065 0.11826788 0.75461287]
 [0.12269936 0.84934657 0.80175384 0.69874657 0.56724597 0.5899097
  0.8078234  0.95171254 0.7718632  0.15178564]
 [0.94512698 0.93803624 0.52115558 0.82617366 0.00798147 0.47090454
  0.31834151 0.85280491 0.81820163 0.3272691 ]
 [0.12354248 0.63231393 0.57539825 0.60492957 0.3453949  0.77871822
  0.42239115 0.36243902 0.01955632 0.82879552]
 [0.06787958 0.03661658 0.63449488 0.60353737 0.21873366 0.98520648
  0.51007694 0.52656298 0.23039749 0.10462207]
 [0.86640193 0.28128894 0.51351886 0.61144039 0.61421799 0.8830711
  0.09876276 0.72149297 0.04281587 0.92325369]
 [0.02679373 0.00776494 0.79621052 0.07888983 0.883955   0.37425122
  0.57502493 0.05850334 0.69568543 0.43375341]
 [0.14801293 0.58058965 0.80649955 0.54938513 0.93494108 0.2169649
  0.44992304 0.0

In [ ]:
arr = np.random.randint(0,5,(10,5))
print(arr)
print(arr.shape, len(arr))

[[4 1 4 3 3]
 [4 4 1 0 1]
 [2 2 2 1 1]
 [3 2 1 1 0]
 [3 4 1 1 3]
 [0 0 4 4 3]
 [2 4 3 3 1]
 [3 0 3 1 0]
 [2 3 3 0 0]
 [3 0 1 3 4]]
(10, 5) 10


####  Exercise 9: Create a numpy array from the given `List`.

Hint: np.array

In [ ]:
x = [10,20,40]
print(len(x))
x = np.array(x)
print(len(x), x.shape)

3
3 (3,)


####  Exercise 10: Matrix multiplication for 1-D array.

To multiply the matrix a and b.

Hint: np.dot

In [ ]:
a = np.array([9, 5, 7, 4])
b = np.array([9, 5, 4, 3])
print(a.shape, b.shape)

prod = np.dot(a,b)
print(prod)


(4,) (4,)
146
[81 25 28 12]


####  Exercise 11: Transpose the given array [ [ 1, 2, 3], [ 4, 5, 6],  [ 7, 8, 9], [10, 11, 12] ].
Hint: np.transpose( )

In [ ]:
x = np.array([ [ 1, 2, 3], [ 4, 5, 6], [ 7, 8, 9], [10, 11, 12] ])
print(x.shape)
x = np.transpose(x)
print(x.shape)

(4, 3)
(3, 4)


####  Exercise 12: Given an array *A*, calculate the square root of the elements in it.

Hint: np.sqrt( )

In [ ]:
A = np.arange(1,20)
print(A)
print(np.sqrt(A))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.         4.12310563 4.24264069
 4.35889894]


In [ ]:
print([i.dtype for i in np.sqrt([9,16])])

[dtype('float64'), dtype('float64')]


#### Exercise 13: Concatenate two numpy arrays columnwise  by specifying axis = 1.
Hint: np.concatenate( )

In [ ]:
c =np.array([[1,2],[3,4]])
d =np.array([[5,6],[7,8]])

arr = np.concatenate((c,d), axis=0)
print(arr)

arr = np.concatenate((c,d), axis=1)
print(arr)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


#### Exercise 14: Print the second and the third column for the given multidimensional array.


In [ ]:
a = np.array([[2, 4, 6, 8, 10],
              [3, 6, 9, 12, 15],
              [4, 8, 12, 16, 20]])

print(a[1:3,2:4])
print(a[:,2])

print(a[:,1:5:2])

[[ 9 12]
 [12 16]]
[ 6  9 12]
[[ 4  8]
 [ 6 12]
 [ 8 16]]


In [ ]:
x = [10,20,30,40,50]
print(x[:3])

[10, 20, 30]


####  Exercise 15: For the given multidimensional array:
1. Calculate the mean row wise by specifying axis = 1 and column wise by specifying axis =0.
2. What is the average value of an array?

In [ ]:
array = np.array([[2, 4, 6, 8, 10], [3, 6, 9, 12, 15], [4, 8, 12, 16, 20]])
print(array.shape)
print(array.mean(axis=0), array.mean(axis=1))

(3, 5)
[ 3.  6.  9. 12. 15.] [ 6.  9. 12.]


#### Exercise 16: Create an array of all the even numbers from 30 to 70.

In [ ]:
arr = np.arange(30,71, 2)
print(arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#### Exercise 17: For the given array, get the slice of the first row and print them.

In [ ]:
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])

print(a3[0])

[[10 11 12]
 [13 14 15]
 [16 17 18]]
